CREATE DATABASE QLKhachSan
GO

USE QLKhachSan
GO

CREATE TABLE ChucDanh
(
	ID INT PRIMARY KEY IDENTITY,
	Ten NVARCHAR(100),
	Role INT,
)

CREATE TABLE NhanVien
(
	ID NVARCHAR(20) PRIMARY KEY,
	Ten NVARCHAR(500),
	NgaySinh DATE,
	GioiTinh BIT,
	DiaChi NVARCHAR(500),
	SDT NVARCHAR(12),
	IDChucDanh INT,
	FOREIGN KEY (IDChucDanh) REFERENCES dbo.ChucDanh(ID),
)
GO

CREATE TABLE KhachHang
(
	ID NVARCHAR(20) PRIMARY KEY,
	Cmnd INT NOT NULL,
	Ten NVARCHAR(500),
	NgaySinh DATE,
	GioiTinh NVARCHAR(3),
	DiaChi NVARCHAR(500),
	SDT NVARCHAR(12),
	QuocTich NVARCHAR(50),
)
GO

CREATE TABLE TinhTrangPhong
(
	ID INT PRIMARY KEY IDENTITY,
	Ten NVARCHAR(100),
)

CREATE TABLE LoaiPhong
(
	ID INT PRIMARY KEY IDENTITY,
	TenLoai NVARCHAR(100),
)

CREATE TABLE Phong
(
	ID NVARCHAR(20) PRIMARY KEY,
	IDTinhTrang INT NOT NULL,
	IDLoai INT NOT NULL,
	Gia MONEY,
	FOREIGN KEY (IDTinhTrang) REFERENCES dbo.TinhTrangPhong(ID),
	FOREIGN KEY (IDLoai) REFERENCES dbo.LoaiPhong(ID),
)
GO

CREATE TABLE BangThuePhong
(
	ID NVARCHAR(20) PRIMARY KEY,
	IDPhong NVARCHAR(20) NOT NULL,
	IDKhachHang NVARCHAR(20) NOT NULL,
	NgayDat DATE,
	CheckIn DATE,
	SoNguoi INT,
	IDTinhTrang INT NOT NULL,
	FOREIGN KEY (IDPhong) REFERENCES dbo.Phong(ID),
	FOREIGN KEY (IDKhachHang) REFERENCES dbo.KhachHang(ID),
	FOREIGN KEY (IDTinhTrang) REFERENCES dbo.TinhTrangPhong(ID),
)
GO

CREATE TABLE Users
(
	ID NVARCHAR(100) PRIMARY KEY,
	Pass NVARCHAR(100) NOT NULL,
	IDNhanVien NVARCHAR(20) NOT NULL,
	FOREIGN KEY (IDNhanVien) REFERENCES dbo.NhanVien(ID),
)
GO

CREATE TABLE HoaDon
(
	ID NVARCHAR(10) PRIMARY KEY,
	IDKhachHang NVARCHAR(20),
	TenKhachHang NVARCHAR(100),
	IDPhong NVARCHAR(10),
	LoaiPhong NVARCHAR(10),
	NgayDat DATE,
	NgayThanhToan DATE,
	SoNgayO INT,
	SoNguoi INT,
	TongTien MONEY,
)
GO