//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string ID { get; set; }
        public string IDKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string IDPhong { get; set; }
        public string LoaiPhong { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public int SoNgayO { get; set; }
        public int SoNguoi { get; set; }
        public decimal TongTien { get; set; }
    }
}
